//plik w wiekszosci jest generowany przez NetBeansa, 
//zawiera kilka funkcji pomocniczych potrzbnych do obslugi GUI
//caly projekt stowrzony jest na modelu Model-View-Controler
//funkcje widoku pelni klasa FarbyUI, modelu - Maszyna, a kontrolere - Kontroler
package moje.farby;

import java.io.*;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;

//klasa widoku
public class FarbyUI extends javax.swing.JFrame {
    //instancja kontrolera 
    private Kontroler kontroler;
    //atrybut potrzeby, zeby sprawdzac, czy zmiane w polach tekstowych zostala 
    //wykonana przez uzytowkonika czy przez wczytywanie atrybutow farby wynranej
    //z listy 
    private Boolean czyKliknalUzytkownik;
   
    public FarbyUI() {
        initComponents();
    }
    
    //dodatkowy kostruktor inicjalizujacy kontroler
    public FarbyUI(Kontroler kontroler) {
        this();
        jButtonUzyjPigmentu.setEnabled(false);
        this.kontroler = kontroler;
        kontroler.ustawGui(this);
        czyKliknalUzytkownik = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaKonsola = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxToksycznosc = new javax.swing.JComboBox<>();
        jTextFieldNazwaFarby = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldToksycznoscFarby = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jButtonDodajPigment = new javax.swing.JButton();
        jButtonDodajFarbe = new javax.swing.JButton();
        jTextFieldPierwszaFarba = new javax.swing.JTextField();
        jTextFieldDrugaFarba = new javax.swing.JTextField();
        jTextFieldToksycznoscPigmentu = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldJakoscFarby = new javax.swing.JTextField();
        jTextFieldNazwaPigmentu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jTextFieldJakoscPigmentu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxJakosc = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonMieszaj = new javax.swing.JButton();
        jButtonUzyjPigmentu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextAreaKonsola.setColumns(20);
        jTextAreaKonsola.setRows(5);
        jScrollPane3.setViewportView(jTextAreaKonsola);

        jComboBoxToksycznosc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "x", "+", "-" }));
        jComboBoxToksycznosc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxToksycznoscActionPerformed(evt);
            }
        });

        jLabel3.setText("Kolor farby: ");

        jTextFieldToksycznoscFarby.setName("Toksycznosc "); // NOI18N
        jTextFieldToksycznoscFarby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldToksycznoscFarbyActionPerformed(evt);
            }
        });

        jLabel8.setText("Współczynnik jakości: ");

        jLabel7.setText("Współczynnik toksyczności: ");

        jList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jList2);

        jButtonDodajPigment.setText("Dodaj pigment");
        jButtonDodajPigment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajPigmentActionPerformed(evt);
            }
        });

        jButtonDodajFarbe.setText("Dodaj farbę");
        jButtonDodajFarbe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajFarbeActionPerformed(evt);
            }
        });

        jTextFieldPierwszaFarba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPierwszaFarbaActionPerformed(evt);
            }
        });

        jTextFieldDrugaFarba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDrugaFarbaActionPerformed(evt);
            }
        });

        jTextFieldToksycznoscPigmentu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldToksycznoscPigmentuActionPerformed(evt);
            }
        });

        jLabel9.setText("Początkowa farba:  ");

        jLabel2.setText("Pigmenty:");

        jLabel10.setText("Końcowa farba: ");

        jTextFieldJakoscFarby.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJakoscFarbyActionPerformed(evt);
            }
        });

        jLabel5.setText("Jakość:  ");

        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jTextFieldJakoscPigmentu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldJakoscPigmentuActionPerformed(evt);
            }
        });

        jLabel1.setText("Farby:");

        jLabel4.setText("Toksyczność: ");

        jComboBoxJakosc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "x", "+", "-" }));
        jComboBoxJakosc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxJakoscActionPerformed(evt);
            }
        });

        jLabel6.setText("Nazwa pigmentu: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonDodajFarbe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(214, 214, 214)
                                .addComponent(jTextFieldNazwaFarby))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldJakoscFarby, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldToksycznoscFarby, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldDrugaFarba, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldPierwszaFarba, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxJakosc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxToksycznosc, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldJakoscPigmentu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldToksycznoscPigmentu, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButtonDodajPigment, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNazwaPigmentu, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPane1, jScrollPane2});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTextFieldDrugaFarba, jTextFieldPierwszaFarba});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldNazwaFarby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldNazwaPigmentu, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jComboBoxToksycznosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldToksycznoscFarby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldToksycznoscPigmentu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldJakoscPigmentu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxJakosc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTextFieldPierwszaFarba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextFieldDrugaFarba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10)))
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jTextFieldJakoscFarby, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonDodajFarbe, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDodajPigment))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8, jLabel9});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTextFieldDrugaFarba, jTextFieldJakoscPigmentu, jTextFieldNazwaFarby, jTextFieldNazwaPigmentu, jTextFieldPierwszaFarba, jTextFieldToksycznoscPigmentu});

        jButtonMieszaj.setText("Mieszaj");
        jButtonMieszaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMieszajActionPerformed(evt);
            }
        });

        jButtonUzyjPigmentu.setText("Użyj pigmentu");
        jButtonUzyjPigmentu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUzyjPigmentuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonUzyjPigmentu, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                    .addComponent(jButtonMieszaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonMieszaj, jButtonUzyjPigmentu});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButtonMieszaj, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUzyjPigmentu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButtonMieszaj, jButtonUzyjPigmentu});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //obsluguje mieszanie, a nastepnie probuje ustawic nowy parametr farny
    //jezeli sie nie uda to wyswietla okno dialogowe z informacja o bledzie 
    private void jTextFieldToksycznoscFarbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldToksycznoscFarbyActionPerformed
        obsluzMieszanie();
        Farba farba = dajAktualnaFarbe();
        if (!farba.ustawToksycznosc(jTextFieldToksycznoscFarby.getText()))
            wypiszBald(Blad.ZLY_PARAMETR);
    }//GEN-LAST:event_jTextFieldToksycznoscFarbyActionPerformed

    //rozpoczyna operacje mieszania
    private void jButtonMieszajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMieszajActionPerformed
        //jezeli nie zostala wybrana farba, wyswietla ono dialogowe 
        if (jList1.isSelectionEmpty())
            wypiszBald(Blad.BRAK_FARBY);
        else {
            obsluzMieszanie();
            ustawWybranaFarbeNaMieszana();
            wypiszNaKonsole("Zaczynam mieszanie");
            wypiszMieszanaFarbeNaKonsole();
            //wlacza przycisk Uzyj pigmentu
            jButtonUzyjPigmentu.setEnabled(true);
        }
    }//GEN-LAST:event_jButtonMieszajActionPerformed

    //wczytuje wybrana farbe z listy
    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        //informuje widok, ze w czasie trwania tej funkcji pola wczytywane do
        //textfieldow NIE sa edytowane przez uzytkowania 
        ustawyCzyKliknalUzytkownik(false);
        String nazwaFarby = jList1.getSelectedValue();
        wyswietlFarbe(nazwaFarby);
        jTextFieldNazwaFarby.setEditable(false);
        ustawyCzyKliknalUzytkownik(true);
    }//GEN-LAST:event_jList1MouseClicked

    //analogicznie jak w przypadku z toksycznoscia farby
    private void jTextFieldJakoscFarbyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJakoscFarbyActionPerformed
        obsluzMieszanie();
        Farba farba = dajAktualnaFarbe();
        if (!farba.ustawJakosc(jTextFieldJakoscFarby.getText()))
            wypiszBald(Blad.ZLY_PARAMETR);
    }//GEN-LAST:event_jTextFieldJakoscFarbyActionPerformed

    //nie sprawdzamy czy jest aktywne mieszanie, bo perzycisk mozna uzyc dopiero
    //wtedy kiedy tak jest
    private void jButtonUzyjPigmentuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUzyjPigmentuActionPerformed
        //jezeli nie wybrano pigmentu
        if (jList2.isSelectionEmpty())
            wypiszBald(Blad.BRAK_PIGMENTU);
        else {
            //jezeli nie udalo sie pomieszac pigmentu
            if (!mieszajWybranyPigment())
                wypiszBald(Blad.ZLY_PIGMENT);
            else {
                //wypiszujemy informacje o udanym mieszaniu na konsole
                wypiszNaKonsole("************************************");
                wypiszMieszanyPigmentNaKonsole();
                wypiszMieszanaFarbeNaKonsole();
            }
        }
    }//GEN-LAST:event_jButtonUzyjPigmentuActionPerformed
    
    //analogicznie jak z parametrami farb
    private void jTextFieldPierwszaFarbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPierwszaFarbaActionPerformed
        obsluzMieszanie();
        Pigment pigment = dajAktualnyPigment();
        if (!pigment.ustawPierwszaFarba(jTextFieldPierwszaFarba.getText()))
            wypiszBald(Blad.ZLY_PARAMETR);
    }//GEN-LAST:event_jTextFieldPierwszaFarbaActionPerformed

    //analogicznie jak z parametrami farb
    private void jTextFieldDrugaFarbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDrugaFarbaActionPerformed
        obsluzMieszanie();
        Pigment pigment = dajAktualnyPigment();
        if (!pigment.ustawDrugaFarba(jTextFieldDrugaFarba.getText()))
            wypiszBald(Blad.ZLY_PARAMETR);
    }//GEN-LAST:event_jTextFieldDrugaFarbaActionPerformed

    //tutaj jednoczesnie ustawiamy dwa pola, bo ParametrPigemntu trzyma iformacje
    //o znaku, uwaga nie mozemy brac informacji o pigmencie od samych pol tekstowych 
    //bo moze sie okazac, ze ktores nie bedzie jeszcze zainicjalizowane 
    private void jTextFieldToksycznoscPigmentuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldToksycznoscPigmentuActionPerformed
        obsluzMieszanie();
        Pigment pigment = dajAktualnyPigment();
        String znak = pigment.dajToksycznosc().wypiszZnak();
        String liczba = jTextFieldToksycznoscPigmentu.getText();
        String kompresja = znak + liczba; 
        if (!pigment.ustawToksycznosc(kompresja))
            wypiszBald(Blad.ZLY_PARAMETR);
    }//GEN-LAST:event_jTextFieldToksycznoscPigmentuActionPerformed

    //analogicznie jak w przypadku farby
    private void jList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList2MouseClicked
        ustawyCzyKliknalUzytkownik(false);
        String nazwaPigmentu = jList2.getSelectedValue();
        wyswietlPigment(nazwaPigmentu);
        jTextFieldNazwaPigmentu.setEditable(false);
        ustawyCzyKliknalUzytkownik(true);
    }//GEN-LAST:event_jList2MouseClicked

    //podobnie jak zmiana wartosci parametru pola z wartoscia toksycznosci
    private void jComboBoxToksycznoscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxToksycznoscActionPerformed
        obsluzMieszanie();
        Pigment pigment = dajAktualnyPigment();
        String znak = jComboBoxToksycznosc.getSelectedItem().toString();
        String liczba = pigment.dajToksycznosc().wypiszLiczba();
        String kompresja = znak + liczba; 
        if (!pigment.ustawToksycznosc(kompresja))
            wypiszBald(Blad.ZLY_PARAMETR);
    }//GEN-LAST:event_jComboBoxToksycznoscActionPerformed

    //analogicznie jak w przypadku tokstycznosci 
    private void jComboBoxJakoscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxJakoscActionPerformed
        obsluzMieszanie();
        Pigment pigment = dajAktualnyPigment();
        String znak = jComboBoxJakosc.getSelectedItem().toString();
        String liczba = pigment.dajJakosc().wypiszLiczba();
        String kompresja = znak + liczba; 
        if (!pigment.ustawJakosc(kompresja))
            wypiszBald(Blad.ZLY_PARAMETR);    }//GEN-LAST:event_jComboBoxJakoscActionPerformed

    //analogicznie jak w przyadku toksycznosci 
    private void jTextFieldJakoscPigmentuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldJakoscPigmentuActionPerformed
        obsluzMieszanie();
        Pigment pigment = dajAktualnyPigment();
        String znak = pigment.dajJakosc().wypiszZnak();
        String liczba = jTextFieldJakoscPigmentu.getText();
        String kompresja = znak + liczba; 
        if (!pigment.ustawJakosc(kompresja))
            wypiszBald(Blad.ZLY_PARAMETR);
    }//GEN-LAST:event_jTextFieldJakoscPigmentuActionPerformed

    //dodaje losowa farbe 
    private void jButtonDodajFarbeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajFarbeActionPerformed
        kontroler.dodajLosowaFarbeDoMaszyny();
    }//GEN-LAST:event_jButtonDodajFarbeActionPerformed

    //dodaje losowy pigment
    private void jButtonDodajPigmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajPigmentActionPerformed
        kontroler.dodajLosowyPigmentDoMaszyny();
    }//GEN-LAST:event_jButtonDodajPigmentActionPerformed
    
    
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FarbyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FarbyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FarbyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FarbyUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //tworzymy GUI
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Kontroler kontroler = new Kontroler();
                try {
                    FileReader strumien = new FileReader("maszyna.conf");
                    new FarbyUI(kontroler).setVisible(true);
                    new Maszyna(strumien, kontroler);
                }
                catch (FileNotFoundException | ReadingException ex) {
                    wypiszBald(Blad.BLAD_WCZYTYWANIA);
                    System.exit(1);
                }
                catch (IOException ex) {
                    System.out.println(ex.getMessage());
                    System.exit(1);
                } 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDodajFarbe;
    private javax.swing.JButton jButtonDodajPigment;
    private javax.swing.JButton jButtonMieszaj;
    private javax.swing.JButton jButtonUzyjPigmentu;
    private javax.swing.JComboBox<String> jComboBoxJakosc;
    private javax.swing.JComboBox<String> jComboBoxToksycznosc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaKonsola;
    private javax.swing.JTextField jTextFieldDrugaFarba;
    private javax.swing.JTextField jTextFieldJakoscFarby;
    private javax.swing.JTextField jTextFieldJakoscPigmentu;
    private javax.swing.JTextField jTextFieldNazwaFarby;
    private javax.swing.JTextField jTextFieldNazwaPigmentu;
    private javax.swing.JTextField jTextFieldPierwszaFarba;
    private javax.swing.JTextField jTextFieldToksycznoscFarby;
    private javax.swing.JTextField jTextFieldToksycznoscPigmentu;
    // End of variables declaration//GEN-END:variables


    private void ustawyCzyKliknalUzytkownik(Boolean czy) {
        czyKliknalUzytkownik = czy;
    }

    private Boolean dajCzyKliknalUzytkownik() {
        return czyKliknalUzytkownik;
    }

    //dodaje farme tylko do widoku
    public void dodajFarbe(String nazwa) {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (int i = 0; i < jList1.getModel().getSize(); i++) {
            model.addElement(jList1.getModel().getElementAt(i));
        }
        model.addElement(nazwa);
        jList1.setModel(model);
    }

    //analogicznie jak przy farbie
    public void dodajPigment(String nazwa) {
        DefaultListModel<String> model = new DefaultListModel<>();
        for (int i = 0; i < jList2.getModel().getSize(); i++) {
            model.addElement(jList2.getModel().getElementAt(i));
        }
        model.addElement(nazwa);
        jList2.setModel(model);
    }

    //wpisuje do odpowiednich pol teksowych parametry farby 
    private void wyswietlFarbe(String nazwa) {
        Farba farba = kontroler.dajFarbeOdMaszyny(nazwa);
        jTextFieldNazwaFarby.setText(farba.dajNazwa());
        jTextFieldToksycznoscFarby.setText(farba.wypiszToksycznosc());
        jTextFieldJakoscFarby.setText(farba.wypiszJakosc());
    }

    //analogicznie jak z farba
    private void wyswietlPigment(String nazwa) {
        Pigment pigment = kontroler.dajPigmentOdMaszyny(nazwa);
        jTextFieldNazwaPigmentu.setText(pigment.dajNazwa());
        jComboBoxToksycznosc.setSelectedItem(pigment.dajToksycznosc().wypiszZnak());
        jTextFieldToksycznoscPigmentu.setText(pigment.dajToksycznosc().wypiszLiczba());
        jComboBoxJakosc.setSelectedItem(pigment.dajJakosc().wypiszZnak());
        jTextFieldJakoscPigmentu.setText(pigment.dajJakosc().wypiszLiczba());
        jTextFieldPierwszaFarba.setText(pigment.dajPierwszaFarbe());
        jTextFieldDrugaFarba.setText(pigment.dajDrugaFarbe());
    }

    //czy zachodzi mieszanie 
    private Boolean czyJestMieszanie() {
        return jButtonUzyjPigmentu.isEnabled();
    }

    //sprawdza czy jest mieszanie i czy miana w polu nastapila przez klikniecie uzytkowanika
    //jezeli tak to konczy mieszanie i wpisuje odpowiedni komunikat na konsole
    private void obsluzMieszanie() {
        if(czyJestMieszanie() && dajCzyKliknalUzytkownik()) {
            jButtonUzyjPigmentu.setEnabled(false);
            wypiszNaKonsole("\nKoniec mieszania\n");
        }
    }

    private void ustawWybranaFarbeNaMieszana() {
        kontroler.ustawMieszanaFarbeDoMaszyny(dajAktualnaFarbe());
    }

    //miesza pigment z farba w maszynie 
    private Boolean mieszajWybranyPigment() {
        return kontroler.mieszajWMaszynie(dajAktualnyPigment());
    }

    //jezeli nie istenieje mieszana farba to nie jest okreslone co zwraca
    private Farba dajMieszanaFarbe() {
        return kontroler.dajMieszanaFrabeOdMaszyny();
    }

    //otwiera okono dialogowe z odpowiednia informacja o obledzie 
    private static void wypiszBald(Blad blad) {
        switch(blad) {
            case ZLY_PARAMETR:
                JOptionPane.showMessageDialog(new JFrame(), "Podano niepoprawny parametr");
                break;
            case ZLY_PIGMENT:
                JOptionPane.showMessageDialog(new JFrame(), "Brak możliwości mieszania farby z tym pigmentem, proszę podać inny pigment");
                break;
            case BLAD_WCZYTYWANIA:
                JOptionPane.showMessageDialog(new JFrame(), "Błąd wczytywania danych z pliku");
                break;
            case BRAK_FARBY:
                JOptionPane.showMessageDialog(new JFrame(), "Proszę najpierw wybrać farbę");
                break;
            case BRAK_PIGMENTU:
                JOptionPane.showMessageDialog(new JFrame(), "Proszę najpierw wybrać pigment");
                break;    
        }
    }

    //daje aktualnie wybrana farbe z listy, a doklaniej to z pola z informacja o 
    //nazwie farby. Jezeli farba nie jest wybrana to nie jest okreslone co zwraca
    private Farba dajAktualnaFarbe() {
            String nazwa = jTextFieldNazwaFarby.getText();
            return kontroler.dajFarbeOdMaszyny(nazwa);
    }

    //analogicznie jak z farba
    private Pigment dajAktualnyPigment() {
        String nazwa = jTextFieldNazwaPigmentu.getText();
        return kontroler.dajPigmentOdMaszyny(nazwa);
    }

    //ponizsze funkcje wypisuja odpowiednie komunikaty na konsole

    private void wypiszNaKonsole(String komunikat) {
        jTextAreaKonsola.append(komunikat + "\n");
    }

    private void wypiszMieszanaFarbeNaKonsole() {
        wypiszNaKonsole("\nNazwa mieszanej farby: " + dajMieszanaFarbe().dajNazwa());
        wypiszNaKonsole("Toksyczność: " + dajMieszanaFarbe().wypiszToksycznosc());
        wypiszNaKonsole("Jakość: " + dajMieszanaFarbe().wypiszJakosc());
    }

    private void wypiszMieszanyPigmentNaKonsole() {
        wypiszNaKonsole("Nazwa mieszanego pigmentu: " + dajAktualnyPigment().dajNazwa());
        wypiszNaKonsole("Współczynnik toksyczności: " + dajAktualnyPigment().dajToksycznosc().wypiszSkompresowane());
        wypiszNaKonsole("Współczynnik jakości: " + dajAktualnyPigment().dajJakosc().wypiszSkompresowane());
    }

}
